task animals completed
tetit/GoHW pull request #5
Opened 2022-07-06 20:24 UTC by tetit

2022-07-06 20:33 UTC, andstepko requested changes

2022-07-06 20:33 UTC, andstepko commented on farmAnimals/struct.go
> +type foodPerDay struct {
Оця структура не потрібна, вона заплутує. Кожен тип тварини має сам говорити скільки їжі потрібно тому чи іншому екземпляру.

2022-07-06 21:28 UTC, tetit commented on farmAnimals/struct.go
> +type foodPerDay struct {
виправила

2022-07-07 09:53 UTC, andstepko requested changes

2022-07-07 09:53 UTC, andstepko commented on farmAnimals/struct.go
> +	foodPerDay float64
Це значення залежить від ваги собаки, воно не є атрибутом екземпляру собаки, а повинно розраховуватись кожен раз, коли необхідно дізнатись скільки на місяць їсть ця собака.
Така структура дозволяє створити собаку, яка не їстиме взагалі, або їстиме більше ніж велика корова. Це поршує умови задачі.

2022-07-07 10:32 UTC, tetit commented on farmAnimals/struct.go
> +	foodPerDay float64
виправила

2022-07-07 10:58 UTC, andstepko approved these changes
Тепер в цілому добре, повторне рвʼю не потрібне, лишив ще 1 коментар.

2022-07-07 10:58 UTC, andstepko commented on farmAnimals/struct.go
> +	dogFoodPerDay = float64(10) / (5 * 30)
Так не в кожному ж місяці 30 днів 🙂 
Умова задачі насправді не вимагала розраховувати в днях.

2022-07-07 11:08 UTC, tetit commented on farmAnimals/struct.go
> +	dogFoodPerDay = float64(10) / (5 * 30)
Дякую за коментарі, просто хотіла зробити можливість розрахунку їжі на різну кількість днів)

2022-07-07 18:51 UTC, merged